# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Maximilian Schambach
email: maximilian.schambach@merantix.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal website of Maximilian Schambach.
github_username: MaxSchambach
minimal_mistakes_skin: "custom"
search: false

repository: MaxSchambach/MaxSchambach.github.io
github: [metadata]

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
locale: "en-US"

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
# paginate_path: /page:num/
paginate_path: /news/page:num/
timezone: DE # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Maximilian Schambach"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Research Team Lead at Merantix Momentum"
  location : "Berlin, Germany"
  links:
    - label: "E-Mail"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:maximilian.schambach@merantix.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MaxSchambach"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      url: "https://gitlab.com/MaxSchambach"
    - label: "Google Scholar"
      icon: "fa fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=fu0gmbAAAAAJ&hl=de&oi=ao"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/maximilian-schambach-a75997190/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MaxSchambach"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      url: "https://gitlab.com/MaxSchambach"
    - label: "Google Scholar"
      icon: "fa fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=fu0gmbAAAAAJ&hl=de&oi=ao"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/maximilian-schambach-a75997190/"

defaults:
  # news
  - scope:
      path: "news/_posts"
      type: posts
    values:
      layout: single
      show_date: true
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: false

  # publications
  - scope:
      path: "publications"
      type: posts
    values:
      layout: single
      show_date: true
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: false

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

  # news
  - scope:
      path: "news"
      type: posts
    values:
      layout: home
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
# tag_archive:
#   type: liquid
#  path: /tags/
